version: "1.0"
info:
  model: int-scaffold
packages:
- name: Vikashdevspro06Project
  gitServerName: VikashgithubRepo
  gitUrl: https://github.com/vikashsharma387
  gitUsername: vikashsharma387
  gitBranch: main
